lib: CARROT-607: Lucene upgraded to version 3.0.0 lib: Google Collections upgraded to version 1.0.0 carrot2-source-lucene: CARROT-608: a possible NoClassDefFoundError fixed, unit test added
git-svn-id: file:///home/dweiss/carrot2/migration/carrot2.svn/trunk@3871 7ff1d41c-760d-0410-a7ff-a3a56f310b35